AllCops:
  Exclude:
  - 'vendor/**/*'
  - 'spec/fixtures/**/*'
  - 'tmp/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - 'rabbitek.gemspec'
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15
