language: ruby
cache: bundler
rvm:
  - 2.6.1
before_install:
  - bundle config set deployment 'true'
  - bundle config set path ${BUNDLE_PATH:-vendor/bundle}
install: bundle install --jobs=3 --retry=3
